# Generated by Django 4.1 on 2022-08-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/users/no-image.png', null=True, upload_to='users/'),
        ),
    ]
